# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndivualTeamMatchPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cones_on_goal', models.IntegerField()),
                ('mobile_goals_scored_in_5', models.IntegerField()),
                ('mobile_goals_scored_in_10', models.IntegerField()),
                ('mobile_goals_scored_in_20', models.IntegerField()),
                ('robot_parks', models.BooleanField()),
                ('autonomous_points', models.IntegerField()),
                ('autonomous_description', models.CharField(max_length=700)),
                ('teleop_description', models.CharField(max_length=700)),
                ('penalties', models.IntegerField()),
                ('penalties_point_deductions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_score', models.IntegerField()),
                ('blue_score', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='blue1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue1', to='api.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue2', to='api.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='red1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red1', to='api.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='red2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red2', to='api.Team'),
        ),
        migrations.AddField(
            model_name='indivualteammatchperformance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
    ]
