# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.AddField(
            model_name='indivualteammatchperformance',
            name='autonomous_cones_stacked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indivualteammatchperformance',
            name='autonomous_mobile_goals_scored_in_10',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indivualteammatchperformance',
            name='autonomous_mobile_goals_scored_in_20',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indivualteammatchperformance',
            name='autonomous_mobile_goals_scored_in_5',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indivualteammatchperformance',
            name='higest_stack_in_10',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indivualteammatchperformance',
            name='higest_stack_in_20',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indivualteammatchperformance',
            name='higest_stack_in_5',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='robot_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='sku',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
