# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170808_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
