# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_team_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='organization',
            new_name='organisation',
        ),
        migrations.AddField(
            model_name='indivualteammatchperformance',
            name='match',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Match'),
            preserve_default=False,
        ),
    ]
