# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170809_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sku',
        ),
        migrations.AddField(
            model_name='team',
            name='grade',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='school',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
